// Triggers a real browser download of a mock file (demo only — no backend yet)
export function downloadMock(filename, content) {
  const body =
    content ||
    `${filename}\n\nGenerated by BuildQ AI — demo export.\n${new Date().toLocaleString('en-NG')}\n`
  const blob = new Blob([body], { type: 'text/plain;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  a.remove()
  URL.revokeObjectURL(url)
}
